version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: effinnov-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: effinnov-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: effinnov
      MYSQL_USER: effinnov
      MYSQL_PASSWORD: effinnov
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: effinnov-pma
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  db_data: